Repository manikumarreddyu/AgroTech-AI, pull requests merged in 2024-11, with the labels that each got.

#737 Added Profile Page to the application
  frontend/src/AgroShopAI/components/ShopNavbar.jsx
  frontend/src/AgroShopAI/pages/Profile.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#740 Add Remember me
  agro-quiz-app/package-lock.json
  agro-quiz-app/package.json
  backend/controllers/authController.js
  frontend/src/components/LoginPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#742 [FEAT] Integrated Profile Page with Backend and Created new APIS
  backend/controllers/shop/brandController.js
  backend/controllers/shop/cartController.js
  backend/controllers/shop/categoryController.js
  backend/controllers/shop/productController.js
  backend/controllers/shop/profileController.js
  backend/controllers/shop/reviewController.js
  backend/controllers/shop/sellerController.js
  backend/controllers/shop/variantController.js
  backend/controllers/shop/wishlistController.js
  backend/model/shop/extendedUser.js
  backend/routes/shop.js
  frontend/src/AgroShopAI/pages/Profile.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#745 Add forgot password
  backend/.env.sample
  backend/controllers/authController.js
  backend/model/user.js
  backend/routes/auth.js
  frontend/src/MainContent.jsx
  frontend/src/components/ForgotPassword.jsx
  frontend/src/components/LoginPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#749 Implemented Dynamic Banner loading at Category Page and Improved Homepage Responsiveness
  frontend/src/AgroShopAI/components/BottomCardContainer.jsx
  frontend/src/AgroShopAI/components/Categories.jsx
  frontend/src/AgroShopAI/pages/CategoryPage.jsx
  frontend/src/AgroShopAI/utils/home-data.js
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#751 Add email verification
  backend/controllers/authController.js
  backend/model/user.js
  backend/routes/auth.js
  frontend/src/MainContent.jsx
  frontend/src/components/EmailVerification.jsx
  frontend/src/components/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#762 Add Google Login
  backend/.env.sample
  backend/index.js
  backend/model/user.js
  backend/package-lock.json
  backend/package.json
  backend/routes/googleauth.js
  backend/services/passport.js
  frontend/src/assets/icons/icons8-google.svg
  frontend/src/components/LoginPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#759 ratingpopup : #750 done
  frontend/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#763 Remove the Dark Mode and Chatbot | Issue #747
  frontend/src/components/models/Fertilizer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#764 Enhance the Irrigation Task Reminder UI | Issue #748
  frontend/src/components/tools/TaskReminder.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#755 Added AES Encryption with Cipher Block Chaining to Payment Method Details
  backend/.env.sample
  backend/controllers/shop/profileController.js
  backend/middleware/encryptionMiddleware.js
  backend/model/shop/extendedUser.js
  backend/routes/shop.js
  frontend/src/AgroShopAI/pages/Profile.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#769 Add Cancellation and Return Policy Page with Footer Navigation
  frontend/src/AgroShopAI/components/ShopFooter.jsx
  frontend/src/AgroShopAI/pages/FooterPages/CancelAndReturn.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#778 Add Docker Containerization
  Docker-compose.yml
  backend/Dockerfile
  frontend/Dockerfile
Labels: gssoc-ext, hacktoberfest-accepted, level3

#790 Add rent-products APIs
  backend/controllers/rent/RentProductController.js
  backend/index.js
  backend/model/rent/rentProduct.js
  backend/routes/rent/rentProductRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#791 Add discussion APIs
  backend/controllers/discussionController.js
  backend/index.js
  backend/model/comment.js
  backend/model/post.js
  backend/routes/discussionRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#793 Add categories and filter implementation
  backend/controllers/rent/RentProductController.js
  backend/index.js
  backend/routes/rent/rentProductRoutes.js
  frontend/src/AgroRentAI/NavigateProducts.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#797 Added Complete Functionality to Search Bar
  backend/controllers/shop/utilityController.js
  backend/routes/shop.js
  frontend/src/AgroShopAI/components/ShopNavbar.jsx
  frontend/src/AgroShopAI/components/sub-components/SearchBar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#801 Add file upload using Multer and Github
  backend/.env.sample
  backend/package-lock.json
  backend/package.json
  backend/routes/rent/rentProductRoutes.js
  backend/services/rent/githubService.js
  backend/uploads/f5324a2b8554ba6da5f0076157866a4e
Labels: gssoc-ext, hacktoberfest-accepted, level3

#803 Fixed vercel Backend Login issue
  backend/index.js
  frontend/src/AgroRentAI/NavigateProducts.jsx
  frontend/src/AgroRentAI/components/AgriProductListing.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/ForgotPassword.jsx
  frontend/src/components/SignUpPage.jsx
  frontend/src/pages/Contact.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#805 Add user dashboard
  frontend/src/AgroRentAI/RentUserDashboard.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#808 Added Gemini AI Chat (Backend + Frontend) | Issue #765
  backend/.env.sample
  backend/index.js
  backend/package.json
  backend/routes/geminiChatRoute.js
  frontend/package.json
  frontend/src/MainContent.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/tools/GeminiChat.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#812 Add admin dashboard
  frontend/package-lock.json
  frontend/src/AgroRentAI/RentAdminDashboard.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#811 Added FAQ Page
  frontend/src/AgroShopAI/components/ShopFooter.jsx
  frontend/src/AgroShopAI/pages/Faq.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#813 Add RentProduct details
  backend/package-lock.json
  frontend/src/AgroRentAI/NavigateProducts.jsx
  frontend/src/AgroRentAI/RentProductDetails.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#819 Added Privacy policy page
  frontend/src/AgroShopAI/components/ShopFooter.jsx
  frontend/src/AgroShopAI/pages/FooterPages/Privacy.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#821 Revamp the Agro Rent Navigate products page.
  frontend/src/AgroRentAI/NavigateProducts.jsx
  frontend/src/AgroRentAI/index.css
  frontend/src/components/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#823 Added Fully Responsive and Dedicated Licensing Page | Issue #810
  frontend/src/MainContent.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Licensing.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#824 Added Fully Responsive and Dedicated Code of Conduct Page | Issue #809
  frontend/src/MainContent.jsx
  frontend/src/components/CodeOfConduct.jsx
  frontend/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#828 Add Product Search Functionality and Result Page
  backend/controllers/shop/utilityController.js
  backend/routes/shop.js
  frontend/src/AgroShopAI/components/CategoriesBanner.jsx
  frontend/src/AgroShopAI/components/sub-components/SearchBar.jsx
  frontend/src/AgroShopAI/pages/SearchResult.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#831 Add Checkout page
  frontend/src/AgroRentAI/RentCheckoutPage.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#835 [FIX] : Signup Schema Error
  backend/controllers/authController.js
  backend/model/user.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#834 Add discussions page implementation
  frontend/src/MainContent.jsx
  frontend/src/components/Discussions.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#836 Add Contributor Page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/MainContent.jsx
  frontend/src/components/Footer.jsx
  frontend/src/pages/ContributorsPage.jsx
  frontend/src/styles/ContributorsPage.css
Labels: gssoc-ext, hacktoberfest-accepted, level3

#837 Table of contents update in readme file
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#842 Add product listing
  frontend/src/AgroRentAI/RentAdminDashboard.jsx
  frontend/src/components/NewsForum.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#846 Integrate Grievance Submission Page with Backend and Create Grievance APIs
  backend/controllers/shop/grievanceController.js
  backend/controllers/shop/profileController.js
  backend/model/shop/grievance.js
  backend/package.json
  backend/routes/shop.js
  frontend/src/AgroShopAI/components/LoginPrompt.jsx
  frontend/src/AgroShopAI/pages/Cart.jsx
  frontend/src/AgroShopAI/pages/FooterPages/Grievance.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#847 Add Dynamic API calls
  frontend/src/components/EmailVerification.jsx
  frontend/src/components/LoginPage.jsx
  frontend/src/components/Profile.jsx
  frontend/src/components/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#848 Add rent cart page
  frontend/src/AgroRentAI/Cart.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#783 ADD Q&A Suggestion Template
  .github/ISSUE_TEMPLATE/config.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#856 Add Wishlist Implementation
  backend/controllers/rent/RentWishlistController.js
  backend/index.js
  backend/model/user.js
  backend/routes/rent/rentWishlistRoutes.js
  frontend/src/AgroRentAI/NavigateProducts.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#858 Remove arrow icon from navbar links
  frontend/src/components/Navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#857 Add Account Verification, Username, and Email Validation
  backend/controllers/authController.js
  backend/model/user.js
  backend/routes/auth.js
  backend/services/emailUtils.js
  frontend/.env.sample
  frontend/src/components/EmailVerification.jsx
  frontend/src/components/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#859 Add to cart Implementaions
  backend/controllers/rent/RentCartController.js
  backend/index.js
  backend/model/user.js
  backend/package-lock.json
  backend/routes/rent/rentCartRoutes.js
  frontend/src/AgroRentAI/Cart.jsx
  frontend/src/AgroRentAI/RentProductDetails.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#865 Implemented Email Resend on Signup, Verification Check on Login, and Automatic Deletion of Unverified Accounts
  backend/controllers/authController.js
  backend/controllers/userController.js
  backend/index.js
  backend/model/user.js
  backend/package.json
  backend/routes/auth.js
  frontend/src/MainContent.jsx
  frontend/src/components/LoginPage.jsx
  frontend/src/components/ResendVerification.jsx
  frontend/src/components/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#866 Fixed CORS Setting for the backend
  backend/index.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#871 Add Admin Login Form with Validation and Enhanced Functionality
  frontend/src/AgroShopAI/components/Pages/Admin-login.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#872 Add Admin Dashboard with Grievances Management and Enhanced Functionality
  frontend/src/AgroShopAI/components/Pages/Admin-Dashboard.jsx
  frontend/src/AgroShopAI/components/Pages/components/DashboardStats.jsx
  frontend/src/AgroShopAI/components/Pages/components/GrievanceList.jsx
  frontend/src/AgroShopAI/components/Pages/components/Header.jsx
  frontend/src/AgroShopAI/components/Pages/components/Sidebar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#874 Implement Shipping Address Schema and CRUD Operations with Advanced Features
  backend/controllers/shop/sub-controllers/shippingAddressController.js
  backend/model/shop/sub-model/ShippingAddress.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#876 Add Order History Page with Status Tags for Admin
  frontend/src/AgroShopAI/components/Pages/Order-history.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#879 Added Order Tracking Schema and Controllers with advance features
  backend/controllers/shop/sub-controllers/orderController.js
  backend/controllers/shop/sub-controllers/orderTrackingController.js
  backend/model/shop/sub-model/OrderHistory.js
  backend/model/shop/sub-model/OrderTracking.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#873 Add user profile sections
  backend/controllers/rent/RentWishlistController.js
  backend/package-lock.json
  frontend/src/AgroRentAI/RentUserDashboard.jsx
  frontend/src/AgroRentAI/components/OrderTracking.jsx
  frontend/src/AgroRentAI/components/RatingReviews.jsx
  frontend/src/AgroRentAI/components/RentalHistory.jsx
  frontend/src/AgroRentAI/components/SecurityPrivacyComponent.jsx
  frontend/src/AgroRentAI/components/Subscription.jsx
  frontend/src/AgroRentAI/components/SupportAssistance.jsx
  frontend/src/AgroRentAI/components/Wishlist.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#878 Update the user information from the Profile Page
  backend/controllers/authController.js
  backend/controllers/userController.js
  backend/model/user.js
  backend/routes/auth.js
  frontend/src/AgroRentAI/RentUserDashboard.jsx
  frontend/src/AgroRentAI/components/AccountInformation.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#890 Add email rental confirmation
  backend/controllers/rent/RentOrderController.js
  backend/index.js
  backend/routes/rent/rentOrderRoutes.js
  frontend/src/AgroRentAI/Cart.jsx
  frontend/src/AgroRentAI/RentCheckoutPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#891 Add reviews/feedback to rentals
  backend/controllers/rent/RatingController.js
  backend/index.js
  backend/model/rent/rentProduct.js
  backend/routes/rent/ratingRoutes.js
  frontend/src/AgroRentAI/RentUserDashboard.jsx
  frontend/src/AgroRentAI/components/RatingReviews.jsx
  frontend/src/AgroRentAI/components/RentalHistory.jsx
  frontend/src/AgroRentAI/components/Wishlist.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#892 Added Coupon Discount System with Controllers, Schema, Middleware, and Utils
  backend/controllers/shop/sub-controllers/couponController.js
  backend/middleware/sub-ware/validateCoupon.js
  backend/model/shop/sub-model/couponModel.js
  backend/routes/sub-routes/couponRoutes.js
  backend/services/sub-service/couponValidator.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#893 Implemented Product Return Feature with routes, schema and Controllers for advance feature
  backend/controllers/shop/sub-controllers/returnController.js
  backend/model/shop/sub-model/ReturnProduct.js
  backend/routes/sub-routes/returnRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#894 Implemented Coupon Management with Coupon Creation and Edit Feature
  frontend/src/AgroShopAI/components/Pages/DiscountCouponManagement.jsx
  frontend/src/AgroShopAI/components/Pages/components/CouponForm.jsx
  frontend/src/AgroShopAI/components/Pages/components/CouponTable.jsx
  frontend/src/AgroShopAI/components/Pages/components/DeleteConfirmationModal.jsx
  frontend/src/AgroShopAI/components/Pages/components/FilterBar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#895 Integrate AI-Supported Chatbot for Enhanced User Assistance
  frontend/src/MainContent.jsx
  frontend/src/components/AiChatbot.jsx
  frontend/src/pages/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#896 Added testimonial with good UI
  frontend/src/components/GoTop.tsx
  frontend/src/components/TestimonialSlider.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#899 Add Full "Return Page" for Tracking and Managing Product Returns
  frontend/src/AgroShopAI/components/Pages/ReturnPage.jsx
  frontend/src/AgroShopAI/components/Pages/components/ReturnFilter.jsx
  frontend/src/AgroShopAI/components/Pages/components/ReturnHeader.jsx
  frontend/src/AgroShopAI/components/Pages/components/ReturnHistory.jsx
  frontend/src/AgroShopAI/components/Pages/components/ReturnModal.jsx
  frontend/src/AgroShopAI/components/Pages/components/ReturnProductCard.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#903 Create Seller Dashboard Page with Product Management, Order Management, and Account Settings
  frontend/src/AgroShopAI/components/Pages/SellerDashboard.jsx
  frontend/src/AgroShopAI/components/Pages/components/SellerAnalyticsPage.jsx
  frontend/src/AgroShopAI/components/Pages/components/SellerDashboardPage.jsx
  frontend/src/AgroShopAI/components/Pages/components/SellerNav.jsx
  frontend/src/AgroShopAI/components/Pages/components/SellerOrderManagementPage.jsx
  frontend/src/AgroShopAI/components/Pages/components/SellerProductManagementPage.jsx
  frontend/src/AgroShopAI/components/Pages/components/SellerSettingsPage.jsx
  frontend/src/AgroShopAI/components/Pages/components/Sellerheader.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#906 Added Statistics Dashboard to Admin Dashboard with Analytical Tools
  frontend/src/AgroShopAI/components/Pages/Admin-Dashboard.jsx
  frontend/src/AgroShopAI/components/Pages/components/Analysis.jsx
  frontend/src/AgroShopAI/components/Pages/components/PopularProducts.jsx
  frontend/src/AgroShopAI/components/Pages/components/SalesTrend.jsx
  frontend/src/AgroShopAI/components/Pages/components/Sidebar.jsx
  frontend/src/AgroShopAI/components/Pages/components/StatCard.jsx
  frontend/src/AgroShopAI/components/Pages/components/StatisticComponent.jsx
  frontend/src/AgroShopAI/components/Pages/components/TimeRangeSelector.jsx
  frontend/src/AgroShopAI/components/Pages/components/UserRegistrations.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#910 Added Customisable Seller Bio and Transparent Store Policies for Enhanced Buyer Trust
  frontend/src/AgroShopAI/components/Pages/SellerDashboard.jsx
  frontend/src/AgroShopAI/components/Pages/components/AboutUsSection.jsx
  frontend/src/AgroShopAI/components/Pages/components/PolicySection.jsx
  frontend/src/AgroShopAI/components/Pages/components/ProfileSection.jsx
  frontend/src/AgroShopAI/components/Pages/components/SellerSettingsPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#916 Add rental APIs
  backend/controllers/rent/RentalController.js
  backend/index.js
  backend/model/rent/rentProduct.js
  backend/model/user.js
  backend/routes/rent/rentalRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#922 Added "Product Entry" Page to Seller Dashboard with Bulk Upload feature
  frontend/src/AgroShopAI/components/Pages/SellerDashboard.jsx
  frontend/src/AgroShopAI/components/Pages/components/CsvUpload.jsx
  frontend/src/AgroShopAI/components/Pages/components/NavigationButtons.jsx
  frontend/src/AgroShopAI/components/Pages/components/ProductEntry.jsx
  frontend/src/AgroShopAI/components/Pages/components/ProductStepForm.jsx
  frontend/src/AgroShopAI/components/Pages/components/SellerNav.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#925 Add admin dash components
  frontend/src/AgroRentAI/RentAdminDashboard.jsx
  frontend/src/AgroRentAI/RentUserDashboard.jsx
  frontend/src/AgroRentAI/components/AdminAnalytics.jsx
  frontend/src/AgroRentAI/components/AdminOrderManagement.jsx
  frontend/src/AgroRentAI/components/AdminProductManagement.jsx
  frontend/src/AgroRentAI/components/AdminUserManagement.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#927 Contributors value showing wrong
  frontend/src/pages/ContributorsPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#929 Complete Inventory Management Module Implementation
  backend/controllers/shop/sub-controllers/inventoryController.js
  backend/middleware/sub-ware/inventoryMiddleware.js
  backend/model/shop/sub-model/InventoryModel.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#930 Added Warehouse Management Module with Controllers, Middleware, and Schema
  backend/controllers/shop/sub-controllers/warehouseController.js
  backend/middleware/sub-ware/warehouseMiddleware.js
  backend/model/shop/sub-model/Warehouse.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#931 Add admin user control APIs
  backend/controllers/rent/AdminUserController.js
  backend/index.js
  backend/model/user.js
  backend/routes/rent/adminUserControlRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#933 extend admin dashboard
  frontend/src/AgroRentAI/RentAdminDashboard.jsx
  frontend/src/AgroRentAI/components/AdminCustomerSupport.jsx
  frontend/src/AgroRentAI/components/AdminMarketing.jsx
  frontend/src/AgroRentAI/components/AdminReport.jsx
  frontend/src/AgroRentAI/components/AdminSalesAnalytics.jsx
  frontend/src/AgroRentAI/components/AdminSecurity.jsx
  frontend/src/AgroRentAI/components/AdminSettings.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#934 Contact Page Revamped | Issue #826
  frontend/src/pages/Contact.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#940 Added Sustainable Water Management Solutions Page | Issue #827
  frontend/src/MainContent.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/models/WaterManagement.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#932 Implemented Flash Sale Page with Filter and Quick Buy features
  frontend/src/AgroShopAI/components/Pages/components/Filter.jsx
  frontend/src/AgroShopAI/components/Pages/components/FlashSaleHeader.jsx
  frontend/src/AgroShopAI/components/Pages/components/ProductCard.jsx
  frontend/src/AgroShopAI/components/Pages/components/ProductList.jsx
  frontend/src/AgroShopAI/components/Pages/components/QuickBuyModal.jsx
  frontend/src/AgroShopAI/components/Pages/components/SalePage.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#942 Added GiftCard page with full features and modular components
  frontend/src/AgroShopAI/components/Pages/GiftBenefit.jsx
  frontend/src/AgroShopAI/components/Pages/GiftCard.jsx
  frontend/src/AgroShopAI/components/Pages/GiftFaq.jsx
  frontend/src/AgroShopAI/components/Pages/GiftIdeas.jsx
  frontend/src/AgroShopAI/components/Pages/GiftLetter.jsx
  frontend/src/AgroShopAI/components/Pages/GiftTest.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#950 Implement order management from admin
  backend/model/user.js
  frontend/src/AgroRentAI/components/AdminOrderManagement.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#951 Implement Return Panel for Managing Return and Refund Requests
  frontend/src/AgroShopAI/components/Pages/Admin-Dashboard.jsx
  frontend/src/AgroShopAI/components/Pages/ReturnPage.jsx
  frontend/src/AgroShopAI/components/Pages/components/ReturnAdminFilter.jsx
  frontend/src/AgroShopAI/components/Pages/components/ReturnAdminHeader.jsx
  frontend/src/AgroShopAI/components/Pages/components/ReturnAdminHistory.jsx
  frontend/src/AgroShopAI/components/Pages/components/ReturnAdminModal.jsx
  frontend/src/AgroShopAI/components/Pages/components/ReturnAdminProductCard.jsx
  frontend/src/AgroShopAI/components/Pages/components/ReturnPage.jsx
  frontend/src/AgroShopAI/components/Pages/components/Sidebar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#952 AddedSupplier Management, Product Management, Search, and Filter Features to Backend
  backend/controllers/shop/sub-controllers/supplierController.js
  backend/middleware/sub-ware/authSupplierMiddleware.js
  backend/middleware/sub-ware/validationMiddleware.js
  backend/model/shop/sub-model/Supplier.js
  backend/routes/sub-routes/supplierRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#954 Add Payment Schema, Controllers, and Admin-Restricted Management Routes for Backend
  backend/controllers/shop/sub-controllers/adminController.js
  backend/controllers/shop/sub-controllers/paymentController.js
  backend/middleware/sub-ware/validatePaymentInvoice.js
  backend/model/shop/sub-model/payment.js
  backend/routes/sub-routes/paymentRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#955 Added Comprehensive Invoice Management System with Routes, Controllers, and Bulk Operations
  backend/controllers/shop/sub-controllers/invoiceController.js
  backend/model/shop/sub-model/invoice.js
  backend/routes/sub-routes/invoiceRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#957 Developed a Dedicated Admin Page for Product Creation and Updates
  frontend/src/AgroShopAI/components/Pages/Admin-Dashboard.jsx
  frontend/src/AgroShopAI/components/Pages/ProductForm.jsx
  frontend/src/AgroShopAI/components/Pages/ProductList.jsx
  frontend/src/AgroShopAI/components/Pages/ProductManagement.jsx
  frontend/src/AgroShopAI/components/Pages/components/Header.jsx
  frontend/src/AgroShopAI/components/Pages/components/Sidebar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#958 Added Full Affiliate Program Page with Join Section and Marketing Materials
  frontend/src/AgroShopAI/components/Pages/Affiliate.jsx
  frontend/src/AgroShopAI/components/Pages/components/AffiliateDashboard.jsx
  frontend/src/AgroShopAI/components/Pages/components/AffiliateHeader.jsx
  frontend/src/AgroShopAI/components/Pages/components/AffiliateJoinSection.jsx
  frontend/src/AgroShopAI/components/Pages/components/AffiliateMarketingMaterials.jsx
  frontend/src/AgroShopAI/components/Pages/components/AffiliateTerms.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#959 Added Trending Products Page with Search, Sort, and Product Grid
  frontend/src/AgroShopAI/components/Pages/Trending.jsx
  frontend/src/AgroShopAI/components/Pages/components/Banner.jsx
  frontend/src/AgroShopAI/components/Pages/components/ProductGrid.jsx
  frontend/src/AgroShopAI/components/Pages/components/SearchAndSort.jsx
  frontend/src/AgroShopAI/components/Pages/components/THeader.jsx
  frontend/src/AgroShopAI/components/Pages/components/TProductCard.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#960 Added `Bundle` Page Component with Featured Product Bundles and Related Suggestions
  frontend/src/AgroShopAI/components/Pages/BulkPage.jsx
  frontend/src/AgroShopAI/components/Pages/BundleCard.jsx
  frontend/src/AgroShopAI/components/Pages/BundleData.js
  frontend/src/AgroShopAI/components/Pages/BundleHeader.jsx
  frontend/src/AgroShopAI/components/Pages/BundleList.jsx
  frontend/src/AgroShopAI/components/Pages/BundleLoyaltyMessage.jsx
  frontend/src/AgroShopAI/components/Pages/BundleOverview.jsx
  frontend/src/AgroShopAI/components/Pages/BundlePriceBreakdown.jsx
  frontend/src/AgroShopAI/components/Pages/BundleProductList.jsx
  frontend/src/AgroShopAI/components/Pages/BundleRelatedItems.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#953 Add user management
  frontend/src/AgroRentAI/RentAdminDashboard.jsx
  frontend/src/AgroRentAI/components/AdminUserManagement.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#956 Add analytics APIs
  backend/controllers/rent/AnalyticsController.js
  backend/index.js
  backend/model/rent/analytics.js
  backend/routes/rent/analyticsRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#966 Fixed climate location search + added debounce
  frontend/src/components/help/Climate.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#967 FIx : Backend Down due to Minor Spell Mistake in Rent Routes
  backend/routes/rent/analyticsRoutes.js
Labels: gssoc-ext, level1

#968 Implemented Loyalty Points System with Schema, Controllers, and Routes
  backend/controllers/shop/sub-controllers/loyaltyPointsController.js
  backend/model/shop/sub-model/loyaltyPointModel.js
  backend/routes/sub-routes/loyaltyPointsRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#969 Implement Referral System with Schema, Controllers, Routes, and Logging
  backend/controllers/shop/sub-controllers/referralController.js
  backend/model/shop/sub-model/Referral.js
  backend/routes/sub-routes/referralRoutes.js
  backend/services/sub-service/logger.js
  backend/services/sub-service/referralFunc.js
  backend/services/sub-service/referralUtils.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#970 Implemented Gift Card System with Creation, Redemption, and Management Features
  backend/controllers/shop/sub-controllers/giftCardController.js
  backend/middleware/sub-ware/giftCardMiddleware.js
  backend/model/shop/sub-model/GiftCard.js
  backend/routes/sub-routes/giftCardRoutes.js
  backend/services/sub-service/giftCardUtils.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#971 Implemented Support Ticket System with CRUD Operations, Assignment, and Status Tracking
  backend/controllers/shop/sub-controllers/ticketController.js
  backend/middleware/sub-ware/ticketMiddleware.js
  backend/model/shop/sub-model/TIcket.js
  backend/routes/sub-routes/ticketRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#972 Added Ticket Page with Ticket Management, Filters, and Header Banner
  frontend/src/AgroShopAI/components/Pages/ConfirmationMessage.jsx
  frontend/src/AgroShopAI/components/Pages/TicketDetailModal.jsx
  frontend/src/AgroShopAI/components/Pages/TicketFilters.jsx
  frontend/src/AgroShopAI/components/Pages/TicketForm.jsx
  frontend/src/AgroShopAI/components/Pages/TicketList.jsx
  frontend/src/AgroShopAI/components/Pages/TicketUser.jsx
  frontend/src/AgroShopAI/components/Pages/Ticketbanner.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#973 Implemented Ticket Management System for AgroTech Admin
  frontend/src/AgroShopAI/components/Pages/AdminTicket.jsx
  frontend/src/AgroShopAI/components/Pages/AdminTicketDetails.jsx
  frontend/src/AgroShopAI/components/Pages/AdminTicketList.jsx
  frontend/src/AgroShopAI/components/Pages/THeader.jsx
  frontend/src/AgroShopAI/components/Pages/TSearchAndFilter.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#978 Add ratings/reviews on the product details page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/AgroRentAI/RentProductDetails.jsx
  frontend/src/AgroRentAI/components/RatingProductReview.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#988 Add Advanced reviews/rating APIs
  backend/controllers/rent/ReviewControllers.js
  backend/index.js
  backend/model/rent/rentProduct.js
  backend/model/user.js
  backend/package-lock.json
  backend/package.json
  backend/routes/rent/reviewRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#989 Implement Agent Management System with CRUD Operations, Ticket Assignment, and Role-based Access Control
  backend/controllers/shop/sub-controllers/agentController.js
  backend/middleware/sub-ware/agentMiddleware.js
  backend/model/shop/sub-model/Agent.js
  backend/routes/sub-routes/agentRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#990 Added Warehouse Inventory Page with Search, Filter, Edit, Delete, and Upload Functionality
  frontend/src/AgroShopAI/components/Pages/Admin-Warehouse.jsx
  frontend/src/AgroShopAI/components/Pages/DeleteModal.jsx
  frontend/src/AgroShopAI/components/Pages/EditModal.jsx
  frontend/src/AgroShopAI/components/Pages/WareInventoryTable.jsx
  frontend/src/AgroShopAI/components/Pages/WareSearchAndFilter.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#993 Create Profile Edit Page (Admin) with Separated Components
  frontend/src/AgroShopAI/components/Pages/Admin-Dashboard.jsx
  frontend/src/AgroShopAI/components/Pages/components/ActiveSessions.jsx
  frontend/src/AgroShopAI/components/Pages/components/ActivityLog.jsx
  frontend/src/AgroShopAI/components/Pages/components/Message.jsx
  frontend/src/AgroShopAI/components/Pages/components/Notifications.jsx
  frontend/src/AgroShopAI/components/Pages/components/PasswordForm.jsx
  frontend/src/AgroShopAI/components/Pages/components/PersonalInfo.jsx
  frontend/src/AgroShopAI/components/Pages/components/ProfileManage.jsx
  frontend/src/AgroShopAI/components/Pages/components/SecuritySettings.jsx
  frontend/src/AgroShopAI/components/Pages/components/TabNav.jsx
Labels: gssoc-ext, level3

#992 Add customer support
  backend/logs/error.log
  backend/package-lock.json
  backend/package.json
  frontend/src/AgroRentAI/components/RentSupportPage.jsx
  frontend/src/AgroRentAI/components/sub-component/Fa.jsx
  frontend/src/AgroRentAI/components/sub-component/Livechat.jsx
  frontend/src/AgroRentAI/components/sub-component/OrderTracking.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#994 Backend Implementation for Delivery Person Management
  backend/controllers/shop/sub-controllers/deliveryPersonController.js
  backend/middleware/sub-ware/validate.js
  backend/model/shop/sub-model/DeliveryPerson.js
  backend/services/sub-service/hashPassword.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#996 Add Personalization
  frontend/package-lock.json
  frontend/package.json
  frontend/src/AgroRentAI/RentUserDashboard.jsx
  frontend/src/AgroRentAI/components/PersonalizationSettings.jsx
  frontend/src/AgroRentAI/components/RentalReminders.jsx
  frontend/src/AgroRentAI/components/sub-components/Recommendations.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#997 Add Loyalty and rewards APIs
  backend/controllers/rent/RewardsController.js
  backend/index.js
  backend/middleware/rent/loyaltyMiddleware.js
  backend/model/rent/reward.js
  backend/model/user.js
  backend/routes/rent/rewardsRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#998 Order History and Easy Re-Rentals APIs
  backend/controllers/rent/RentOrderController.js
  backend/routes/rent/rentOrderRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#917 Add Authentication checks for AGRO-rent services
  backend/middleware/authMiddleware.js
  backend/routes/rent/rentCartRoutes.js
  backend/routes/rent/rentProductRoutes.js
  backend/routes/rent/rentWishlistRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#1002 Promotions and Deals Management APIs
  backend/controllers/rent/SeasonalPricingController.js
  backend/controllers/rent/featuredProductController.js
  backend/controllers/rent/promotionController.js
  backend/index.js
  backend/model/rent/featuredProduct.js
  backend/model/rent/promotion.js
  backend/model/rent/seasonalPricing.js
  backend/routes/rent/featuredProductRoutes.js
  backend/routes/rent/promotionRoutes.js
  backend/routes/rent/seasonalPricingRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#1003 Add Notification Page for Notices in agrotech
  frontend/src/AgroShopAI/components/Pages/FeaturedProductsSection.jsx
  frontend/src/AgroShopAI/components/Pages/HeroSection.jsx
  frontend/src/AgroShopAI/components/Pages/NotficationHeader.jsx
  frontend/src/AgroShopAI/components/Pages/NotificationPage.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#1006 Add Backend Support for Managing Malfunctioning Products with Enhanced Validation and Error Handling
  backend/controllers/shop/sub-controllers/damagecontroller.js
  backend/model/shop/sub-model/damagemodal.js
  backend/routes/sub-routes/routesdamage
Labels: gssoc-ext, hacktoberfest-accepted, level3

#1008 yield-prediction
  yield-prediction/Crop_Yield_Prediction.csv
  yield-prediction/Crop_Yield_prediction.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level3
