Repository manikumarreddyu/AgroTech-AI, pull requests merged in 2024-10, with the labels that each got.

#100 Update Twitter icon in Footer.jsx
  frontend/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#111 Added Hover effect on Button
  frontend/src/components/CropRecommendation.jsx
  frontend/src/components/Disease.jsx
  frontend/src/components/Fertilizer.jsx
  frontend/src/components/SoilQuality.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#101 Added the contact.jsx page and made the changes in Home.jsx and App.jsx.
  frontend/src/App.jsx
  frontend/src/pages/Contact.jsx
  frontend/src/pages/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#124 added rate us option
  frontend/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#128 sugarcane_disease_pred
  .gitattributes
  notebooks/Sugarcane Disease Prediction/Dataset/readme.md
  notebooks/Sugarcane Disease Prediction/Images/classification_report.png
  notebooks/Sugarcane Disease Prediction/Images/confusion_matrix.png
  notebooks/Sugarcane Disease Prediction/Images/input.png
  notebooks/Sugarcane Disease Prediction/Images/vgg16_graph.png
  notebooks/Sugarcane Disease Prediction/models/ensemble_model.ipynb
  notebooks/Sugarcane Disease Prediction/models/readme.md
  notebooks/Sugarcane Disease Prediction/readme.md
Labels: gssoc-ext, hacktoberfest-accepted, level3

#148 feat:Replacing External Redirection to Tomato Disease Article with Internal Page
  frontend/src/MainContent.jsx
  frontend/src/components/AIEngine.jsx
  frontend/src/pages/Article.jsx
  frontend/src/pages/article.css
Labels: gssoc-ext, hacktoberfest-accepted, level3

#154 added notebook Crop Pest and Disease Detection using DL
  notebooks/Crop Pest and Disease Detection/Dataset/README.md
  notebooks/Crop Pest and Disease Detection/Images/ANN_Training.png
  notebooks/Crop Pest and Disease Detection/Images/CNN_Training.png
  notebooks/Crop Pest and Disease Detection/Images/ResNet(Basic)_Training.png
  notebooks/Crop Pest and Disease Detection/Images/VGG16_Training.png
  notebooks/Crop Pest and Disease Detection/Model/Crop_Pest_and_Disease_Detection_using_DL.ipynb
  notebooks/Crop Pest and Disease Detection/Model/Crop_Pest_and_Disease_Detection_using_DL_.py
  notebooks/Crop Pest and Disease Detection/Model/README.md
  notebooks/Crop Pest and Disease Detection/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level2

#152 chatbot integrated
  Agri_ChatBot/.gitignore
  Agri_ChatBot/requirements.txt
  Agri_ChatBot/src/config.json
  Agri_ChatBot/src/main.py
  frontend/src/MainContent.jsx
  frontend/src/pages/ChatBot.jsx
  frontend/src/pages/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#159 Chatbot message icon floating
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/About.jsx
  frontend/src/pages/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#164 Implemented Character-Based Validation for Contact Form Fields
  frontend/src/pages/Contact.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#160 Rate-us section changes
  frontend/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#165 [Feature]: Implement Irrigation Management System for Optimized Water Usage
  agro/app.py
  agro/irrigation_model.pkl
  disease-prediction-api/label_encoder.pkl
  disease-prediction-api/label_encoder.py
  frontend/package-lock.json
  frontend/src/MainContent.jsx
  frontend/src/assets/img10.jpg
  frontend/src/assets/img11.jpg
  frontend/src/assets/img12.jpg
  frontend/src/assets/img13.jpg
  frontend/src/assets/img14.png
  frontend/src/components/Irrigation.jsx
  frontend/src/components/Navbar.jsx
  irrigation_model.pkl
  notebooks/irrigation.py
  simulated_irrigation_data.csv
Labels: gssoc-ext, hacktoberfest-accepted, level3

#169 Improve CSS of Language Selector Button and Remove "Powered by" Text from Google Translate Widget
  frontend/src/components/GoogleTranslate.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#166 Improve the Prices Section
  frontend/src/components/Prices.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#173 Fix Navbar distortion caused by the addition of "Irrigation system" item
  frontend/src/components/Navbar.jsx
  frontend/src/components/Prices.jsx
  frontend/src/components/Reports.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#189 Added Crop Rotation Recommendation Model and Dataset
  crop-rotation-api/app.py
  notebooks/Crop-Rotation-Recommendation/Crop_Rotation_Recommendation.ipynb
  notebooks/Crop-Rotation-Recommendation/crop_recommendation_dataset_100000.csv
Labels: gssoc-ext, hacktoberfest-accepted, level3

#196 Fixed the issues in the contact page the commented parts i fixed.
  frontend/src/pages/Contact.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#200 Changed the logos in the contact page
  frontend/src/pages/Contact.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#214 Backend API for Sugarcane Disease Prediction Model
  sugarcane-disease-api/app.py
  sugarcane-disease-api/models/Readme.md
  sugarcane-disease-api/prediction.py
  sugarcane-disease-api/requirements.txt
  sugarcane-disease-api/uploaded_image/readme.md
Labels: gssoc-ext, hacktoberfest-accepted, level3

#211 Preview image
  frontend/src/components/AIEngine.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#221 Add Frontend for Sugarcane Disease Prediction Backend
  frontend/src/App.jsx
  frontend/src/MainContent.jsx
  frontend/src/components/AIEngine.jsx
  frontend/src/components/Disease.jsx
  frontend/src/components/Submit.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#228 fixed cards and added readmore button
  frontend/src/components/Disease.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#234 Enhanced Navbar functionalities with added logo function
  frontend/src/components/Navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#235 Added the Advantages and Disadvantages cards with framer motion and special Effects in the Fertilizer, Irrigation and soil section
  frontend/src/components/AdvantagesDisadvantages.jsx
  frontend/src/components/CropRecommendation.jsx
  frontend/src/components/Fertilizer.jsx
  frontend/src/components/Irrigation.jsx
  frontend/src/components/SoilQuality.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#236 Enhanced styling of FAQ
  frontend/src/components/FAQ.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#249 Merge branch 'main' of https://github.com/manikumarreddyu/AgroTech-AI
  frontend/index.html
  frontend/public/intro.mp4
  frontend/src/assets/114
Labels: gssoc-ext, hacktoberfest-accepted, level3

#256 Redesigned the entire Hero Section and Home page with elegant look and better UI experience
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Features.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#262 Result Page for Sugarcane prediction
  frontend/public/show-more.png
  frontend/src/MainContent.jsx
  frontend/src/assets/crops/rice.png
  frontend/src/components/AIEngine.jsx
  frontend/src/components/Disease.jsx
  frontend/src/components/sugarcane-result-template.jsx
  sugarcane-disease-api/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level3

#279 Update README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2

#281 Setup for Authentication backend
  e-commerce-backend/.env
  e-commerce-backend/index.js
  e-commerce-backend/middleware/auth.js
  e-commerce-backend/model/user.js
  e-commerce-backend/package-lock.json
  e-commerce-backend/routes/auth.js
  frontend/src/App.jsx
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level3

#286 Redesigned the Disease Detection page
  frontend/src/assets/crops/allcrops.png
  frontend/src/components/Disease.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#292 Created Mushroom Edibility Prediction API
  README.md
  mushroom-edibility/app.py
  mushroom-edibility/data/__pycache__/maps.cpython-311.pyc
  mushroom-edibility/data/maps.py
  mushroom-edibility/data/mushrooms.csv
  mushroom-edibility/models/encoders.pkl
  mushroom-edibility/models/model.pkl
  mushroom-edibility/notebook/mushroom-classification.ipynb
  mushroom-edibility/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level3

#290 Explore more page which is a compilled library of all the functions in the website created.
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/MainContent.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Products.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#310 Update Climate.jsx
  frontend/src/components/Climate.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#312 Redesigned the current crop fertilizer prediction UI to a better level dashboard and intutive design
  frontend/src/components/Fertilizer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#313 Enhanced styles and formatting
  frontend/src/pages/ChatBot.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#318 #275 solved
  frontend/calculators/CropYield.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#319 Add Rental Landing Page
  frontend/src/MainContent.jsx
  frontend/src/assets/images/tools.jpeg
  frontend/src/assets/rental.jpg
  frontend/src/components/Footer.jsx
  frontend/src/pages/Rental.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#328 [FIX] : Remove Empty `div` from GoogleTranslator Component
  frontend/src/components/GoogleTranslate.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#333 Feat/add fertilizer calculator
  frontend/src/MainContent.jsx
  frontend/src/components/FertilizerCalculator.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#334 Modified the Soil Quality Prediction, How it works and the forms in the better and elegant UI
  frontend/src/.env
  frontend/src/components/SoilQuality.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#338 404 page added
  frontend/src/MainContent.jsx
  frontend/src/NotFound.jsx
Labels: gssoc-ext, level2

#339 Enhanced the necessity, map and the advanatages and disadvantages section with soil quality prediction
  frontend/src/components/AdvantagesDisadvantages.jsx
  frontend/src/components/SoilQuality.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#340 Create Eco-Crop Manager
  Eco-Crop Manager
Labels: gssoc-ext, hacktoberfest-accepted, level2

#346 Added logout functionality and authentication context
  backend/routes/auth.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/MainContent.jsx
  frontend/src/components/AuthPage.jsx
  frontend/src/components/LoginPage.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/SignUpPage.jsx
  frontend/src/context/AuthContext.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#351 Create Crop Management Guide
  Crop Management Guide
Labels: gssoc-ext, hacktoberfest-accepted, level2

#353 Redesigned and Improve the Login & Sign Up UI
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/LoginImage.png
  frontend/src/assets/SignUpImage.png
  frontend/src/components/LoginPage.jsx
  frontend/src/components/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#369 Solved issue#295
  frontend/src/components/Navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#374 Fixed the Bug of visibility of Soil Type and Crop Type by changing the colors according to the dark mode
  frontend/package-lock.json
  frontend/src/components/Fertilizer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#380 Fixed the Text in the dark mode properly by providing text-black
  frontend/src/components/Fertilizer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#381 Added the Terms and Conditions page
  frontend/src/MainContent.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/TermsAndConditions.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#384 Added the cookie policy page
  frontend/src/MainContent.jsx
  frontend/src/components/CookiePolicy.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#386 Improved E-commerce UI
  e-commerce-backend/package-lock.json
  e-commerce-backend/package.json
  e-commerce-frontend/package-lock.json
  e-commerce-frontend/src/page/Home.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#407 Fix/adjust UI alignment for tools
  frontend/src/components/tools/CropYield.jsx
  frontend/src/components/tools/FertilizerRequirement.jsx
  frontend/src/components/tools/SoilMoisture.jsx
  frontend/src/components/tools/WaterRequirement.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#411 Added authorization to use chatbot, added react toast whenever necessary, solved merge conflicts conflicts with main, why ai, homepage, loginpage and signup page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/LoginPage.jsx
  frontend/src/components/SignUpPage.jsx
  frontend/src/pages/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#412 Node modules deleted.
  frontend/src/App.css
  frontend/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#413 [FEAT]: Added Paddy Disease Prediction Backend with a CNN Model
  paddy-backend-api/app.py
  paddy-backend-api/model/rice_model.h5
  paddy-backend-api/prediction.py
  paddy-backend-api/readme.md
  paddy-backend-api/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level3

#418 Added the the Privacy policy page and fixed redirection issues.
  frontend/package-lock.json
  frontend/src/MainContent.jsx
  frontend/src/components/Feedback.jsx
  frontend/src/components/PrivacyPolicy.jsx
  frontend/src/components/TermsAndConditions.jsx
  rental-frontend/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#419 Animation added to elements : Issue no #233
  frontend/src/pages/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#434 Added Backend API for Soil Testing Labs with Gemini LLM and Plotly Integration
  soil-testing-labs-api/app.py
  soil-testing-labs-api/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level3

#400 Create Online_Farmer_Market
  Online_Farmer_Market
Labels: gssoc-ext, hacktoberfest-accepted, level2

#438 Added the Footer component in the app.jsx
  e-commerce-frontend/src/App.jsx
  e-commerce-frontend/src/component/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#439 Revamp Paddy-Sugarcane Image Upload with Results Container
  frontend/src/MainContent.jsx
  frontend/src/components/Disease.jsx
  frontend/src/pages/Disease/DiseaseRecognition.jsx
  frontend/src/pages/Disease/PaddyRecognition.jsx
  frontend/src/pages/Disease/SugarcaneRecognition.jsx
  paddy-backend-api/uploaded_image/readme.md
Labels: gssoc-ext, hacktoberfest-accepted, level3

#443 Improved home page UI
  e-commerce-frontend/src/page/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#445 added sitemap.xml
  frontend/sitemap.xml
Labels: gssoc-ext, hacktoberfest-accepted, level3

#451 Designed the Hero Section page for AgroRent AI with search buttons and proper effects
  frontend/src/pages/AgroRentalAI/HeroSection.Rentjsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#456 Designed the AgroRental Navigation page for products by conditional redering and elegant look with modern design
  frontend/src/AgroRentAI/HeroSectionRent.jsx
  frontend/src/AgroRentAI/NavigateProducts.jsx
  frontend/src/MainContent.jsx
  frontend/src/assets/banner2.png
Labels: gssoc-ext, hacktoberfest-accepted, level3

#477 Contact us page done backend frontend both : #218 done
  backend/.env.sample
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/routes/Contactroute.js
  frontend/src/assets/contactus.png
  frontend/src/pages/Contact.jsx
  frontend/src/styles/Contact.css
Labels: gssoc-ext, hacktoberfest-accepted, level3

#481 Add pass viewer
  frontend/src/assets/icons/eye-slash.svg
  frontend/src/assets/icons/eye.svg
  frontend/src/components/LoginPage.jsx
  frontend/src/components/SignUpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#484 Added Carousel Hero Section to Home Page
  frontend/public/shop-asset/30-percent.png
  frontend/public/shop-asset/banner_1.jpg
  frontend/public/shop-asset/banner_2.jpg
  frontend/public/shop-asset/banner_3.jpg
  frontend/public/shop-asset/fresh.png
  frontend/public/shop-asset/nurture.png
  frontend/public/shop-asset/pest.png
  frontend/public/shop-asset/sale.png
  frontend/src/AgroShopAI/HeroSectionShop.jsx
  frontend/src/AgroShopAI/HomeShop.jsx
  frontend/src/AgroShopAI/hero-banner.js
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#487 Added electrical and electronics shops finder backend
  electrical-electronics-shops-api/app.py
  electrical-electronics-shops-api/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level3

#497 Deleted previous website images
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#498 [FEAT] Added CardRelay of Top-Selling Items and Categories to Homepage
  frontend/public/shop-asset/30-percent.png
  frontend/public/shop-asset/banner_1.jpg
  frontend/public/shop-asset/banner_2.jpg
  frontend/public/shop-asset/banner_3.jpg
  frontend/public/shop-asset/fresh.png
  frontend/public/shop-asset/nurture.png
  frontend/public/shop-asset/pest.png
  frontend/public/shop-asset/sale.png
  frontend/src/AgroShopAI/HomeShop.jsx
  frontend/src/AgroShopAI/components/CardRelay.jsx
  frontend/src/AgroShopAI/components/Categories.jsx
  frontend/src/AgroShopAI/components/HeroSectionShop.jsx
  frontend/src/AgroShopAI/hero-banner.js
  frontend/src/AgroShopAI/utils/home-data.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#508 Added Agro Quiz App and deployed in vercel
  agro-quiz-app/.eslintrc.json
  agro-quiz-app/.gitignore
  agro-quiz-app/components.json
  agro-quiz-app/next.config.js
  agro-quiz-app/package-lock.json
  agro-quiz-app/package.json
  agro-quiz-app/postcss.config.js
  agro-quiz-app/public/logo.ico
  agro-quiz-app/public/next.svg
  agro-quiz-app/public/vercel.svg
  agro-quiz-app/src/app/favicon.ico
  agro-quiz-app/src/app/globals.css
  agro-quiz-app/src/app/layout.tsx
  agro-quiz-app/src/app/page.tsx
  agro-quiz-app/src/categories.ts
  agro-quiz-app/src/components/ui/button.tsx
  agro-quiz-app/src/lib/ai.ts
  agro-quiz-app/src/lib/common.ts
  agro-quiz-app/src/lib/utils.ts
  agro-quiz-app/tailwind.config.js
  agro-quiz-app/tailwind.config.ts
  agro-quiz-app/tsconfig.json
Labels: gssoc-ext, hacktoberfest-accepted, level3

#517 Done Some Enhancements And Also Added Some New Sections
  CONTRIBUTING.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#519 Margin added to the Tool section of Fertilizer requirement section
  frontend/src/components/tools/FertilizerRequirement.jsx
  frontend/src/index.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#526 Removed API key
  agro-quiz-app/src/lib/ai.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1

#530 Added Responsiveness
  frontend/src/components/AboutUs.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#532 Added More Categories and Enhanced Homepage Aesthetics
  frontend/src/AgroShopAI/HomeShop.jsx
  frontend/src/AgroShopAI/components/CardContainer.jsx
  frontend/src/AgroShopAI/components/CardRelay.jsx
  frontend/src/AgroShopAI/components/Categories.jsx
  frontend/src/AgroShopAI/components/HeroSectionShop.jsx
  frontend/src/AgroShopAI/components/LargeCardContainer.jsx
  frontend/src/AgroShopAI/utils/home-data.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#533 added hovereffect at dropdown navlink for desktop
  frontend/src/components/Navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#539 Added Footer to AgroShop
  frontend/src/AgroShopAI/components/LargeCardContainer.jsx
  frontend/src/AgroShopAI/components/ShopFooter.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#548 Improved stylings for soil testing and electrical electronics shops
  frontend/src/components/ElectricalElectronicsShops.jsx
  frontend/src/components/SoilTestingCenters.jsx
  frontend/src/styles/ElectricalElectronicsShops.css
  frontend/src/styles/SoilTestingCenters.css
Labels: gssoc-ext, hacktoberfest-accepted, level3

#556 Added APIs to handle product data
  backend/.env.sample
  backend/controllers/brandController.js
  backend/controllers/categoryController.js
  backend/controllers/productController.js
  backend/controllers/reviewController.js
  backend/controllers/sellerController.js
  backend/controllers/variantController.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/routes/shop.js
  backend/test/api.test.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#557 Integrated soil testing labs, electronics shops apis along with frontend
  agrotech-ai-apis/.env-sample
  agrotech-ai-apis/app.py
  agrotech-ai-apis/requirements.txt
  frontend/src/components/SoilTestingCenters.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#562 Integrated mushroom edibility api, , model and data with other apis
  agrotech-ai-apis/.gitignore
  agrotech-ai-apis/app.py
  agrotech-ai-apis/data/maps.py
  agrotech-ai-apis/data/mushrooms.csv
  agrotech-ai-apis/models/encoders.pkl
  agrotech-ai-apis/models/model.pkl
  agrotech-ai-apis/mushroom_edibility.py
  agrotech-ai-apis/notebook/mushroom-classification.ipynb
  agrotech-ai-apis/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level3

#568 Added category and product apis for database
  backend/controllers/categoryController.js
  backend/controllers/productController.js
  backend/index.js
  backend/package.json
  backend/routes/shop.js
  backend/test/api.test.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#569 Added Brand and Seller APIs for database
  backend/controllers/brandController.js
  backend/controllers/sellerController.js
  backend/routes/shop.js
  backend/test/api.test.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#580 Added Review and Variant APIs for database
  backend/controllers/reviewController.js
  backend/controllers/variantController.js
  backend/routes/shop.js
  backend/test/api.test.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#593 Connected Frontend and Backend for Dynamic AgroShop Category Page
  backend/controllers/categoryController.js
  backend/controllers/productController.js
  backend/controllers/sellerController.js
  backend/model/shop/product.js
  backend/routes/shop.js
  frontend/src/AgroShopAI/components/Categories.jsx
  frontend/src/AgroShopAI/components/Filter.jsx
  frontend/src/AgroShopAI/components/ProductCard.jsx
  frontend/src/AgroShopAI/pages/CategoryPage.jsx
  frontend/src/AgroShopAI/utils/home-data.js
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#591 Add Pre-Made Prompts to Chatbot Interface for Improved User Engagement
  agrotech-ai-chatbot/src/main.py
  frontend/src/pages/ChatBot.jsx
  package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level3

#601 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#603 Extend User Schema for E-commerce Features
  backend/model/shop/extendedUser.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#613 View Report and Download pdf button functioning in fertilizer prediction page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/models/Fertilizer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#628 Phosphorous level in Fertilizer Page
  frontend/src/components/models/Fertilizer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#630 Update product, variant, review Schema and Implemented New APIs for Product Management
  backend/controllers/brandController.js
  backend/controllers/categoryController.js
  backend/controllers/productController.js
  backend/controllers/reviewController.js
  backend/controllers/sellerController.js
  backend/controllers/variantController.js
  backend/model/shop/product.js
  backend/model/shop/variant.js
  backend/routes/shop.js
  frontend/src/AgroShopAI/components/Filter.jsx
  frontend/src/AgroShopAI/components/ProductCard.jsx
  frontend/src/AgroShopAI/pages/CategoryPage.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#639 Implemented role based access control
  backend/.env.sample
  backend/index.js
  backend/middleware/auth.js
  backend/model/user.js
  backend/routes/auth.js
  backend/routes/users.js
  frontend/src/MainContent.jsx
  frontend/src/components/LoginPage.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/Profile.jsx
  frontend/src/components/SignUpPage.jsx
  frontend/src/context/AuthContext.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#642 Update README.md added Stargazers and Forkers section to readme.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#658 Update README.md Added Table to Display Repository Statistics in README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#660 added detele feature
  frontend/src/components/tools/PlantTaskReminder.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#661 Add Ratings API and frontend
  backend/controllers/rating.js
  backend/index.js
  backend/model/rating.js
  backend/routes/users.js
  frontend/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#668 fix plant-task error
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/tools/PlantTaskReminder.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#667 ADD table of Content and API Documentation on README file
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#671 Enhance and Structure the Contributors Section
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#677 added history feature
  frontend/src/components/tools/TaskReminder.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#678 Fix crop price prediction page
  frontend/src/components/models/Prices.jsx
  package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level1

#681 Creating Backend Schema For Rental and Lease products
  backend/controllers/agriProductController.js
  backend/middleware/authMiddleware.js
  backend/model/AgriProduct.js
  backend/routes/agriProductRoutes.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#683 Create frontend for displaying projects in agro rent page with product card, model and email mock
  frontend/src/AgroRentAI/components/AgriProductListing.jsx
  frontend/src/AgroRentAI/components/ProductCard.jsx
  frontend/src/AgroRentAI/components/ProductModal.jsx
  frontend/src/AgroRentAI/data/products.js
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#697 added history feature
  frontend/src/components/tools/PlantTaskReminder.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#702 Added Cart Page frontend to the agroshop.
  frontend/package.json
  frontend/src/AgroShopAI/components/ProductCard.jsx
  frontend/src/AgroShopAI/pages/Cart.jsx
  frontend/src/AgroShopAI/pages/ProductPage.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#704 enhanced contact us page
  frontend/src/pages/Contact.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#706 [Fixed] Login State Persistence and User Data Return on Login
  backend/controllers/authController.js
  frontend/src/components/LoginPage.jsx
  frontend/src/context/AuthContext.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#715 [FEAT] Integrated Cart Backend with Cart Page, Category Page and Product Page
  backend/.env.sample
  backend/controllers/cartController.js
  backend/model/shop/extendedUser.js
  backend/routes/shop.js
  frontend/.env.sample
  frontend/package.json
  frontend/src/AgroShopAI/components/CartComponents.jsx
  frontend/src/AgroShopAI/components/LoginPrompt.jsx
  frontend/src/AgroShopAI/components/ProductCard.jsx
  frontend/src/AgroShopAI/components/ReviewSection.jsx
  frontend/src/AgroShopAI/pages/Cart.jsx
  frontend/src/AgroShopAI/pages/CategoryPage.jsx
  frontend/src/AgroShopAI/pages/ProductPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#716 Add transitions
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/FAQ.jsx
  frontend/src/styles/Fa.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#719 Added Banners for Each Product Category
  frontend/src/AgroShopAI/assets/category_page/Seeds.png
  frontend/src/AgroShopAI/assets/category_page/animal_husbandary.png
  frontend/src/AgroShopAI/assets/category_page/farm_machinery.png
  frontend/src/AgroShopAI/assets/category_page/fungicide.png
  frontend/src/AgroShopAI/assets/category_page/growth_promoters.png
  frontend/src/AgroShopAI/assets/category_page/herbicide.png
  frontend/src/AgroShopAI/assets/category_page/insecticide.png
  frontend/src/AgroShopAI/assets/category_page/new_product.png
  frontend/src/AgroShopAI/assets/category_page/nutrient.png
  frontend/src/AgroShopAI/assets/category_page/organic.png
Labels: gssoc-ext, hacktoberfest-accepted, level3

#722 Added End-to-End integration of rental, lease and sales products page
  backend/index.js
  frontend/src/AgroRentAI/components/AgriProductListing.jsx
  frontend/src/AgroRentAI/data/products.json
  frontend/src/AgroRentAI/rent-assets/productsBg.png
Labels: gssoc-ext, hacktoberfest-accepted, level3

#723 Improve the UI and add rest of the CRUD features along with email sending for Irrigation Task Reminders
  backend/.env.sample
  backend/controllers/agriProductController.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/routes/agriProductRoutes.js
  backend/services/emailService.js
  frontend/package-lock.json
  frontend/src/components/tools/TaskReminder.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#725 Added navigation bar for cart , account and order
  frontend/src/AgroShopAI/components/ShopNavbar.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#726 redesign the rate us form
  frontend/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#727 Added Wishlist Pages and Backend Integration
  backend/controllers/wishlistController.js
  backend/model/shop/extendedUser.js
  backend/routes/shop.js
  frontend/src/AgroShopAI/components/ProductCard.jsx
  frontend/src/AgroShopAI/components/ShopNavbar.jsx
  frontend/src/AgroShopAI/pages/CategoryPage.jsx
  frontend/src/AgroShopAI/pages/Wishlist.jsx
  frontend/src/MainContent.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#648 Integrate Password Recovery Feature
  frontend/package-lock.json
  frontend/src/MainContent.jsx
  frontend/src/components/LoginPage.jsx
  frontend/src/components/PasswordRecoveryPage.jsx
  frontend/src/components/VerifyOtpPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#701 Added the visitor count
  frontend/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#735 Enhance error handling and logging for API key loading and request pr…
  agrotech-ai-chatbot/src/main.py
Labels: gssoc-ext, hacktoberfest-accepted, level1

#736 Added hacktoberfes and gssoc banners
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1
